### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Carlyx** [YouweiLyu/reflection_separation_with_un-polarized_images#1]
Your work is awesome. When I test real world images, I notice that your code use the data which contains a pair of polarized images（pol1 and pol3).   Whether a pair of images must be used for testing, or a single image can also achieve the purpose of testing?

**Comment by YouweiLyu** [comment]
@Carlyx Actually, A pair of polarized images should be taken as input in our method.

**Comment by Carlyx** [comment]
I see.
Thanks for your reply.
